name: Test

on:
  workflow_dispatch:

jobs:
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build job
    steps:
      - name: setup RELEASE_VERSION
        run: echo "RELEASE_VERSION=2.14.1" >> $GITHUB_ENV

      - name: Login to Jira
        uses: atlassian/gajira-login@master
        env:
            JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
            JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
            JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Create
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: ${{ secrets.JIRA_PROJECT }}
          issuetype: Task
          fields: '{"Priority": "Critical","Components":"Mobile Engage SDK"}'
          summary: |
            New Emarsys SDK release
          description: |
            Emarsys SDK ${{env.RELEASE_VERSION}} has been released!
